server:
  port: 8090
  mode: release

database:
  host: postgres
  port: 5432
  user: xinipay
  password: "XiniPay2026Secure!"
  dbname: xinipay
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "xinipay-jwt-production-secret-key-2026-random"
  expire: 24

license:
  enabled: false
  file_path: "./license.enc"
